name: fork-dataset

imagePullSecrets:
  - name: aws-ecr-secret

tasks:
  fetch-content-set-config:
    container:
      image: 016353724114.dkr.ecr.us-west-1.amazonaws.com/pipeline:fetch-config-46482a5d-20210224
      command: [ sh, -c ]
      args: [ "./fetch-config --app-name=ContentStore --output-file=/tmp/config.yaml" ]
      env:
        - { name: "APOLLO_ADDR", value: "10.19.2.220:8080" }
        - { name: "ENVIRONMENT", value: "fat" }
    outputs:
      artifacts:
        - name: config-file
          path: /tmp/config.yaml

  fetch-label-set-config:
    container:
      image: 016353724114.dkr.ecr.us-west-1.amazonaws.com/pipeline:fetch-config-46482a5d-20210224
      command: [ sh, -c ]
      args: [ "./fetch-config --app-name=LabelStore --output-file=/tmp/config.yaml" ]
      env:
        - { name: "APOLLO_ADDR", value: "10.19.2.220:8080" }
        - { name: "ENVIRONMENT", value: "fat" }
    outputs:
      artifacts:
        - name: config-file
          path: /tmp/config.yaml

  fetch-dataset-config:
    container:
      image: 016353724114.dkr.ecr.us-west-1.amazonaws.com/pipeline:fetch-config-46482a5d-20210224
      command: [ sh, -c ]
      args: [ "./fetch-config --app-name=Dataset --output-file=/tmp/config.yaml" ]
      env:
        - { name: "APOLLO_ADDR", value: "10.19.2.220:8080" }
        - { name: "ENVIRONMENT", value: "fat" }
    outputs:
      artifacts:
        - name: config-file
          path: /tmp/config.yaml

  fork-dataset:
    dependencies:
      - fetch-content-set-config
      - fetch-label-set-config
      - fetch-dataset-config
    container:
      image: 016353724114.dkr.ecr.us-west-1.amazonaws.com/pipeline:fork-dataset-46482a5d-20210225
      command: [ sh, -c ]
      args: [ "./fork-dataset /mnt/configs" ]
      env:
        - { name: "ENVIRONMENT", value: "fat" }
    inputs:
      artifacts:
        - name: content-store-config
          path: /mnt/configs/ContentStore.dev.yaml
        - name: label-store-config
          path: /mnt/configs/LabelStore.dev.yaml
        - name: dataset-config
          path: /mnt/configs/Dataset.dev.yaml
    arguments:
      artifacts:
        - name: content-store-config
          from: "{{tasks.fetch-content-set-config.outputs.artifacts.config-file}}"
        - name: label-store-config
          from: "{{tasks.fetch-label-set-config.outputs.artifacts.config-file}}"
        - name: dataset-config
          from: "{{tasks.fetch-dataset-config.outputs.artifacts.config-file}}"
